columns:
  - price: int64
  - carat: float64
  - cut: object
  - color: object
  - clarity: object
  - depth: float64
  - table: float64
  - x: float64
  - y: float64
  - z: float64
numeric_columns:
  - price
  - carat
  - depth
  - table
  - x
  - y
  - z
categorical_columns:
  - cut
  - color
  - clarity