columns:
  - fare_amount: int
  - pickup_longitude: int
  - pickup_latitude: int
  - dropoff_longitude: int
  - dropoff_latitude: int
  - passenger_count: int

numeric_col:
  - fare_amount: int
  - pickup_longitude: int
  - pickup_latitude: int
  - dropoff_longitude: int
  - dropoff_latitude: int
  - passenger_count: int